Production release:
  - base-branch: ["main", "master"]

Hotfix:
  - head-branch: ["hotfix"]

Has Migrations:
  - "project/**/migrations/*.py"

Dependency updates:
  - "Pipfile"
  - "Pipfile.lock"
  - "**/package.json"
  - "requirements.txt"

Python:
  - "**/*.py"

JavaScript:
  - "**/*.js"
  - "**/*.jsx"

TypeScript:
  - "**/*.ts"
  - "**/*.tsx"

AWS:
  - "project/aws/**"
